- name: Install dependencies for PostgreSQL
  apt: name={{ item }} update_cache=true state=latest
  with_items:
  - bash
  - openssl
  - libssl-dev
  - libssl-doc

- name: Install PostgreSQL
  apt: name={{ item }} update_cache=true state=present
  with_items:
  - postgresql
  - postgresql-contrib
  - libpq-dev
  - python3-psycopg2

- name: Ensure user has access to the new database
  become: true
  become_user: postgres
  postgresql_user: db=postgres
       name={{ db_user }}
       password={{ db_password }}
       priv=ALL
       state=present
