- name: Update and prepare
  hosts: hosts
  become: true
  remote_user: root
  roles:
    - user-setup
  tags:
    - user-setup

- name: Configure UFW
  hosts: hosts
  become: true
  remote_user: root
  roles:
    - ufw
  tags:
    - ufw

- name: Install pip
  hosts: hosts
  become: true
  remote_user: "{{ user }}"
  roles:
    - pip
  tags:
    - pip

- name: Install Postgresql
  hosts: hosts
  become: true
  remote_user: "{{ user }}"
  roles:
    - postgresql
  tags:
    - postgresql

- name: Install git and clone repos
  hosts: hosts
  become: true
  remote_user: "{{ user }}"
  roles:
    - git
  tags:
    - git

- name: Install Grafana
  hosts: hosts
  become: true
  remote_user: "{{ user }}"
  roles:
    - grafana
  tags:
    - grafana
