- name: Create user accounts
  user:
    system: yes
    name: "{{ user }}"
    groups: sudo
    shell: /bin/bash

- name: Set authorized key taken from file
  authorized_key:
    user: "{{ user }}"
    state: present
    key: "{{ lookup('file', '~/.ssh/id_ed25519.pub') }}"

- name: Create wheel group
  group:
    name: wheel
    state: present

- name: Allow wheel group to have passwordless sudo
  lineinfile:
    dest: /etc/sudoers
    state: present
    regexp: '^%wheel'
    line: '%wheel ALL=(ALL) NOPASSWD: ALL'
    validate: 'visudo -cf %s'

- name: Add sudoers users to wheel group
  user:
    name: "{{ user }}"
    groups: wheel
    append: yes
    state: present
    createhome: yes
