- name: Install git
  apt:
    pkg:
      - git

- name: Ensure .ssh directory exists
  file:
    dest: /root/.ssh/
    mode: 0700
    owner: root
    state: directory

- name: Install ssh private key
  copy:
    src: /home/anton/.ssh/id_ed25519
    dest: /root/.ssh/id_ed25519
    mode: 0600
    owner: root

- name: Ensure github.com is a known host
  lineinfile:
    dest: /root/.ssh/known_hosts
    create: yes
    state: present
    line: "{{ lookup('pipe', 'ssh-keyscan -t rsa github.com') }}"
    regexp: "^github\\.com"

- name: Clone garden-of-things git repositories
  git:
    repo: git@github.com:frank690/garden-of-things.git
    dest: /root/garden-of-things

- name: Install garden-of-things
  pip:
    chdir: /root/garden-of-things
    name: .
