- name: Install git
  apt:
    pkg:
      - git

- name: Ensure .ssh directory exists
  file:
    dest: ~/.ssh/
    mode: 0700
    owner: "{{ user }}"
    state: directory

- name: Install ssh private key
  copy:
    src: ~/.ssh/id_ed25519
    dest: ~/.ssh/id_ed25519
    mode: 0600
    owner: "{{ user }}"

- name: Ensure github.com is a known host
  lineinfile:
    dest: ~/.ssh/known_hosts
    create: yes
    state: present
    line: "{{ lookup('pipe', 'ssh-keyscan -t rsa github.com') }}"
    regexp: "^github\\.com"

- name: Clone garden-of-things git repositories
  git:
    repo: git@github.com:frank690/garden-of-things.git
    dest: ~/garden-of-things

- name: Install garden-of-things
  pip:
    chdir: ~/garden-of-things
    name: .

- name: Read the SQL script that comes with the garden-of-things repo
  shell: cat ~/garden-of-things/resources/init.sql
  register: sql_script

- name: Apply SQL script to set up garden-of-things on DB
  become_user: postgres
  postgresql_query:
    db: "{{ db_name }}"
    query: "{{ sql_script }}"
