- name: Install git
  apt:
    pkg:
      - git

- name: Ensure .ssh directory exists
  file:
    dest: ~/.ssh/
    mode: 0700
    owner: "{{ user }}"
    state: directory

- name: Install ssh private key
  copy:
    src: ~/.ssh/id_ed25519
    dest: ~/.ssh/id_ed25519
    mode: 0600
    owner: "{{ user }}"

- name: Ensure github.com is a known host
  lineinfile:
    dest: ~/.ssh/known_hosts
    create: yes
    state: present
    line: "{{ lookup('pipe', 'ssh-keyscan -t rsa github.com') }}"
    regexp: "^github\\.com"

- name: Clone garden-of-things git repositories
  git:
    repo: git@github.com:frank690/garden-of-things.git
    dest: ~/garden-of-things

- name: Install garden-of-things
  pip:
    chdir: ~/garden-of-things
    name: .

- name: Execute preparation script
  command: python3 ~/garden-of-things/resources/preparation.py
